/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoutiqueRouteImport } from './routes/boutique'
import { Route as PanierRouteImport } from './routes/panier'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardProduitsRouteImport } from './routes/dashboard.produits'
import { Route as ProduitProductIdRouteImport } from './routes/produit.$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiqueRoute = BoutiqueRouteImport.update({
  id: '/boutique',
  path: '/boutique',
  getParentRoute: () => rootRouteImport,
} as any)
const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProduitsRoute = DashboardProduitsRouteImport.update({
  id: '/dashboard/produits',
  path: '/dashboard/produits',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitProductIdRoute = ProduitProductIdRouteImport.update({
  id: '/produit/$productId',
  path: '/produit/$productId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boutique': typeof BoutiqueRoute
  '/panier': typeof PanierRoute
  '/dashboard/produits': typeof DashboardProduitsRoute
  '/produit/$productId': typeof ProduitProductIdRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boutique': typeof BoutiqueRoute
  '/panier': typeof PanierRoute
  '/dashboard/produits': typeof DashboardProduitsRoute
  '/produit/$productId': typeof ProduitProductIdRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boutique': typeof BoutiqueRoute
  '/panier': typeof PanierRoute
  '/dashboard/produits': typeof DashboardProduitsRoute
  '/produit/$productId': typeof ProduitProductIdRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/boutique'
    | '/panier'
    | '/dashboard/produits'
    | '/produit/$productId'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/boutique'
    | '/panier'
    | '/dashboard/produits'
    | '/produit/$productId'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/boutique'
    | '/panier'
    | '/dashboard/produits'
    | '/produit/$productId'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoutiqueRoute: typeof BoutiqueRoute
  PanierRoute: typeof PanierRoute
  DashboardProduitsRoute: typeof DashboardProduitsRoute
  ProduitProductIdRoute: typeof ProduitProductIdRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutique': {
      id: '/boutique'
      path: '/boutique'
      fullPath: '/boutique'
      preLoaderRoute: typeof BoutiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/produits': {
      id: '/dashboard/produits'
      path: '/dashboard/produits'
      fullPath: '/dashboard/produits'
      preLoaderRoute: typeof DashboardProduitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produit/$productId': {
      id: '/produit/$productId'
      path: '/produit/$productId'
      fullPath: '/produit/$productId'
      preLoaderRoute: typeof ProduitProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoutiqueRoute: BoutiqueRoute,
  PanierRoute: PanierRoute,
  DashboardProduitsRoute: DashboardProduitsRoute,
  ProduitProductIdRoute: ProduitProductIdRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
